#!/usr/bin/env ruby
module Hipe; end
here = File.dirname(__FILE__)

# require 'rubygems'; require 'ruby-debug'; puts "\e[1;5;33mruby-debug\e[0m"
require 'fileutils'
require "#{here}/hipe-tinyscript/core" unless Hipe.const_defined?('Tinyscript') #etc
require "#{here}/hipe-diff/diff.rb" # careful! pulls in rubygems for diff/lcs

module Flizz; end
Flizz::Config = {
  :simmies => [
    {:src => './the-gibson/nginx-conf', :tgt => '/etc/nginx/conf' },
    {:src => './the-gibson/motion-conf', :tgt => '/etc/motion'    },
    {:src => './hipeland/monit-conf/monitrc', :tgt => '/etc/monitrc', :not_link => 1}
  ],
  :hosts => [
    {:name => 'hipeland' },
    {:name => 'the-gibson' }
  ]
}

module Flizz
  class MyCommand < Hipe::Tinyscript::Command
    def dry_run?; @param[:dry_run] end
  end
  module Commands
    class Symlinks < MyCommand
      description "symlinks -- check'em, make'em"
      parameter '-n', '--dry-run', "don't do eet"
      parameter '-v', '--version', "with non-symlinked configs pull changes back to here"
      parameter :host, Hash[*Config[:hosts].map{|x| [x[:name], x[:name]]}.flatten], '',
        :positional => 1, :required => 1
      def execute
        re = Regexp.new('^'+Regexp.escape("./#{param(:host)}"))
        simmies = Config[:simmies].select{|x| x[:src] =~ re }
        simmies.each{ |simmy| do_simmy(simmy) }
        nil
      end
    private
      def do_simmy simmy
        return not_link(simmy) if simmy[:not_link]
        src, tgt = [simmy[:src], simmy[:tgt]]
        full_src = File.expand_path(src, File.dirname(__FILE__))
        if File.exist?(tgt) || File.symlink?(tgt) # catches bad symlinks
          if File.symlink?(tgt)
            actual_src = File.readlink(tgt) # http://ruby-doc.org/core/classes/File.src/M002534.html
            if actual_src == full_src
              out colorize('ok: ', :green) << "#{tgt} -> #{full_src}"
            else
              out colorize('notice: ', :yellow) << "#{tgt} -> #{actual_src} (! #{full_src})"
              if ! File.exist?(tgt)
                out colorize('notice: ', :yellow) <<
                  "#{colorize(tgt, :magenta)} -> #{actual_src} (target path does not exist)"
              end
            end
          else
            out colorize('notice: ', :yellow) << "not a symlink: #{tgt}"
          end
        else
          FileUtils.ln_s(full_src, tgt, :verbose => 1, :noop => dry_run?)
        end
      end
      def not_link simmy
        full_src = File.expand_path(simmy[:src], File.dirname(__FILE__))
        tgt = simmy[:tgt]
        if File.symlink?(tgt)
          out colorize("error: ", :red) << "cannot be symlink: #{tgt} (per config above)"
        elsif File.exist? tgt
          versioned = File.read(full_src)
          unversioned = File.read(tgt)
          if versioned == unversioned
            out colorize('ok: ', :green) << "#{tgt} == #{full_src} (#{tgt.size} bytes ok)"
          else
            out colorize("diff --git #{full_src} #{tgt}", :yellow)
            out colorize("--- #{full_src}", :yellow)
            out colorize("+++ #{tgt}", :yellow)
            out Hipe::Diff.colorize(versioned, unversioned)
          end
          if @param[:version]
            FileUtils.cp(tgt, full_src, :verbose =>1, :noop => dry_run?)
          end
        else
          fail("no thanks") if File.directory?(full_src)
          FileUtils.cp(full_src, tgt, :verbose => 1, :noop => dry_run?)
        end
      end
    end
  end
end

module Flizz
  class App < Hipe::Tinyscript::App
    commands Commands
    config Config
  end
end

Flizz::App.new.run(ARGV) if File.basename(__FILE__) == File.basename($PROGRAM_NAME)
