#!/usr/bin/env ruby
module Hipe; end
here = File.dirname(__FILE__)

# require 'rubygems'; require 'ruby-debug'; puts "\e[1;5;33mruby-debug\e[0m"
require 'fileutils'
require "#{here}/hipe-tinyscript/core" unless Hipe.const_defined?('Tinyscript') #etc
require 'rubygems' # while we figure out the way to avoid this when using rubygems
require "#{here}/hipe-diff/diff.rb" # careful! pulls in rubygems for diff/lcs

module ConfConf; end
ConfConf::Config = {
  :simmies => [
    {:src => './servers/the-gibson/nginx-conf', :tgt => '/etc/nginx/conf' },
    {:src => './servers/the-gibson/motion-conf', :tgt => '/etc/motion'    },
    {:src => './servers/hipeland/monit-conf/monitrc', :tgt => '/etc/monitrc', :not_link => 1},
    {:src => './servers/hipeland/etc/unicorn/redmine-git.conf.rb', :tgt => '/etc/unicorn/redmine-git.conf.rb' }
  ],
  :hosts => [
    {:name => 'hipeland' },
    {:name => 'the-gibson' }
  ]
}

module ConfConf
  class MyCommand < Hipe::Tinyscript::Command
    def notice msg
      out colorize('notice: ', :yellow) << msg
      nil
    end
  end
  module Commands
    class Sync < MyCommand
      description "symlinks -- check'em, make'em.  pull non-symlinkable confs into scm."
      parameter :nolinks, '-L', "don't do symlinks"
      parameter '-n', '--dry-run', "don't do eet"
      parameter :host, Hash[*Config[:hosts].map{|x| [x[:name], x[:name]]}.flatten], '',
        :positional => 1, :required => 1
      parameter :action, "pull: pull non-symlinkable changes back into scm.",
        "push: push files in scm out to server", {'push'=>'push', 'pull' => 'pull'}, '', :positional => 1
      def execute
        base = "./servers/#{param(:host)}"
        re = Regexp.new('^'+Regexp.escape(base))
        simmies = Config[:simmies].select{|x| x[:src] =~ re }
        return notice("nothing to do for #{base.inspect}") if simmies.empty?
        simmies.each{ |simmy| do_simmy(simmy) }
        nil
      end
    private
      def do_simmy simmy
        return not_link(simmy) if simmy[:not_link]
        return if @param.key? :nolinks
        src, tgt = [simmy[:src], simmy[:tgt]]
        full_src = File.expand_path(src, File.dirname(__FILE__))
        if File.exist?(tgt) || File.symlink?(tgt) # catches bad symlinks
          if File.symlink?(tgt)
            actual_src = File.readlink(tgt) # http://ruby-doc.org/core/classes/File.src/M002534.html
            if actual_src == full_src
              out colorize('ok: ', :green) << "#{tgt} -> #{full_src}"
            else
              out colorize('notice: ', :yellow) << "#{tgt} -> #{actual_src} (! #{full_src})"
              if ! File.exist?(tgt)
                out colorize('notice: ', :yellow) <<
                  "#{colorize(tgt, :magenta)} -> #{actual_src} (target path does not exist)"
              end
            end
          else
            out colorize('notice: ', :yellow) << "not a symlink: #{tgt}"
          end
        else
          FileUtils.ln_s(full_src, tgt, :verbose => 1, :noop => dry_run?)
        end
      end
      def not_link simmy
        full_src = File.expand_path(simmy[:src], File.dirname(__FILE__))
        tgt = simmy[:tgt]
        if File.symlink?(tgt)
          out colorize("error: ", :red) << "cannot be symlink: #{tgt} (per config above)"
        elsif File.exist? tgt
          versioned = File.read(full_src)
          begin
            unversioned = File.read(tgt)
          rescue Errno::EACCES => e
            out colorize('notice: ', :yellow) << e.to_s
            return nil
          end
          if versioned == unversioned
            out colorize('ok: ', :green) << "#{tgt} == #{full_src} (#{tgt.size} bytes ok)"
          else
            out colorize("diff --git #{full_src} #{tgt}", :yellow)
            out colorize("--- #{full_src}", :yellow)
            out colorize("+++ #{tgt}", :yellow)
            out Hipe::Diff.colorize(versioned, unversioned)
          end
          case @param[:action]
          when nil ;
          when 'pull' ;
            FileUtils.cp(tgt, full_src, :verbose =>1, :noop => dry_run?)
          when 'push' ;
            FileUtils.cp(full_src, tgt, :verbose =>1, :noop => dry_run?)
          else fail("unexpected action: #{param[:action]}")
          end
          nil
        else
          fail("no thanks") if File.directory?(full_src)
          FileUtils.cp(full_src, tgt, :verbose => 1, :noop => dry_run?)
        end
      end
    end
  end
end

module ConfConf
  class App < Hipe::Tinyscript::App
    commands Commands
    config Config
  end
end

ConfConf::App.new.run(ARGV) if File.basename(__FILE__) == File.basename($PROGRAM_NAME)
